# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate (estimate) environmental suitability
#'
#' Calculate / estimate the environmental suitability for a given environmental value,
#' based on the three "cardinal" values of the species for that environmental niche.
#'
#' @param vmax `<numeric>` upper (i.e. maximum) tolerable value
#' @param vopt `<numeric>` optimal (i.e. prefered) value
#' @param vmin `<numeric>` lower (i.e. minimum) tolerable value
#' @param venv `<numeric>` environmental value for which to calculate the suitability
#' @return `<numeric>` environmental suitability
#' @details The environmental suitability is calculated based on a beta distribution
#' after a formula provided by Yan & Hunt (1999) (see references paragraph)
#' \deqn{suitability = (\frac{V_{max} - V_{env}}{V_{max} - V_{opt}}) * (\frac{V_{env} - V_{min}}{V_{opt} - V_{min}})^{\frac{V_{opt} - V_{min}}{V_{max} - V_{opt}}}}
#' @note The original formula by Yan & Hunt was only intended to calculate
#' the relative daily growth rate of plants in relation to temperature. The abstraction to
#' use this to A) calculate a niche suitability; and B) use it on other
#' environmental values than temperature might not be valid. However, the assumption that the
#' environmental suitability for one niche dimension is highest at one optimal value and
#' decreases towards the tolerable minumum and maximum values seems reasonable.
#' @references
#' Weikai Yan, L.A. Hunt, (1999)
#' An Equation for Modelling the Temperature Response of Plants using only the Cardinal Temperatures,
#' Annals of Botany,
#' Volume 84, Issue 5,
#' Pages 607-614,
#' ISSN 0305-7364, <doi:10.1006/anbo.1999.0955>
#' @examples
#' calculate_suitability(
#'   vmax = 30,
#'   vopt = 25,
#'   vmin = 10,
#'   venv = 0:40
#' )
#' @export
calculate_suitability <- function(vmax, vopt, vmin, venv) {
    .Call('_metaRange_calculate_suitability', PACKAGE = 'metaRange', vmax, vopt, vmin, venv)
}

#' Undirected and fixed sized dispersal
#'
#' Dispersal function that uses a fixed sized kernel and isn't influenced by
#' the environmental suitability. The individuals in each cell are redistributed to the
#' surrounding cells according to probability defined in the dispersal kernel.
#' Usefull for e.g. wind dispersed plants.
#'
#' @param abundance `<numeric matrix>` Values need to be non-negative.
#' @param dispersal_kernel `<numeric matrix>` Dispersal kernel. Needs to have an odd size.
#' @return `<numeric matrix>` The new abundance matrix.
#' @keywords internal
dispersal_fixed_undirected <- function(abundance, dispersal_kernel) {
    .Call('_metaRange_dispersal_fixed_undirected', PACKAGE = 'metaRange', abundance, dispersal_kernel)
}

#' Directed and fixed sized dispersal
#'
#' Dispersal function that uses a fixed sized kernel and directed dispersal towards suitable areas.
#' Suitable for e.g. animals that can sense their surroundings.
#'
#' @param abundance `<numeric matrix>` Values need to be non-negative.
#' @param suitability `<numeric matrix>` Values need to non-missing and between 0 and 1 for the result to make sense.
#' Needs to have same size as abundance.
#' @param dispersal_kernel `<numeric matrix>` Dispersal kernel. Needs to have an odd size.
#' @return `<numeric matrix>` The new abundance matrix.
#' @keywords internal
dispersal_fixed_directed <- function(abundance, suitability, dispersal_kernel) {
    .Call('_metaRange_dispersal_fixed_directed', PACKAGE = 'metaRange', abundance, suitability, dispersal_kernel)
}

#' Metabolic scaling
#'
#' A function to calculate the metabolic scaling of a parameter, based on the
#' metabolic theory of ecology (Brown et al. 2004).
#'
#' @param normalization_constant `<numeric>` normalization constant.
#' @param scaling_exponent `<numeric>` allometric scaling exponent of the mass.
#' @param mass `<numeric matrix>`  mean (individual) mass.
#' @param temperature `<numeric matrix>` temperature in kelvin (K).
#' @param E `<numeric>` activation energy in electronvolts (eV).
#' @param k `<numeric>` Boltzmann's constant (eV / K).
#' @details
#' The function uses the formula in the form of:
#' \deqn{parameter = normalization\_constant \cdot mass^{scaling\_exponent} \cdot e^{\frac{E}{k \cdot temperature}}}
#' General notes:
#'
#' Reproduction rate is generally assumed to scale with an exponent of `-1/4`
#' and an activation energy of `-0.65 eV` (important: it's negative).
#'
#' Carrying capacity is generally assumed to scale with an exponent of `-3/4`
#' and an activation energy of `0.65 eV` (important: it's positive).
#' But read: (Brown et. al. 2004; Brown & Sibly, 2012) for an in-depth explanation.
#'
#' Units:
#'
#' 1 electronvolt = 1.602176634 * 10^-19 Joule
#'
#' Boltzmann constant 1.380649 * 10^-23 Joule/Kelvin
#'
#' Boltzmann constant in eV/K = 8.617333e-05 = (1.380649 * 10^-23) / (1.602176634 * 10^-19)
#' @references
#' Brown, J.H., Gillooly, J.F., Allen, A.P., Savage, V.M. & West, G.B. (2004).
#' Toward a Metabolic Theory of Ecology. Ecology, 85, 1771–1789.
#' <doi:10.1890/03-9000>
#'
#' Brown, J.H. and Sibly, R.M. (2012). The Metabolic Theory of Ecology and Its Central Equation.
#' In Metabolic Ecology (eds R.M. Sibly, J.H. Brown and A. Kodric-Brown).
#' <doi:10.1002/9781119968535.ch2>
#' @return `<numeric>` The scaled parameter.
#' @examples
#' reproduction_rate <- 0.25
#' E_reproduction_rate <- -0.65
#' estimated_normalization_constant <-
#'     calculate_normalization_constant(
#'         parameter_value = reproduction_rate,
#'         scaling_exponent = -1/4,
#'         mass = 100,
#'         reference_temperature = 273.15 + 10,
#'         E = E_reproduction_rate
#'     )
#' metabolic_scaling(
#'     normalization_constant = estimated_normalization_constant,
#'     scaling_exponent = -1/4,
#'     mass = 100,
#'     temperature = 273.15 + 20,
#'     E = E_reproduction_rate
#' )
#'
#' carrying_capacity <- 100
#' E_carrying_capacity <- 0.65
#' estimated_normalization_constant <-
#'     calculate_normalization_constant(
#'         parameter_value = carrying_capacity,
#'         scaling_exponent = -3/4,
#'         mass = 100,
#'         reference_temperature = 273.15 + 10,
#'         E = E_carrying_capacity
#'     )
#' metabolic_scaling(
#'     normalization_constant = estimated_normalization_constant,
#'     scaling_exponent = -3/4,
#'     mass = 100,
#'     temperature = 273.15 + 20,
#'     E = E_carrying_capacity
#' )
#' @export
metabolic_scaling <- function(normalization_constant, scaling_exponent, mass, temperature, E, k = 8.617333e-05) {
    .Call('_metaRange_metabolic_scaling', PACKAGE = 'metaRange', normalization_constant, scaling_exponent, mass, temperature, E, k)
}

#' Ricker reproduction model
#'
#' An implementation of the "classic" Ricker reproduction model in the form of:
#' \deqn{abundance_{(t+1)} = abundance_t \cdot e^{reproduction_rate \cdot (1 - \frac{abundance_t}{carrying_capacity})}}
#'
#' @param abundance `<numeric>` vector (or matrix) of abundances.
#' @param reproduction_rate `<numeric>` vector (or matrix) of reproduction rates.
#' @param carrying_capacity `<numeric>` vector (or matrix) of carrying capacities.
#' @details Note that the input should have an equal size and that the input abundance
#' should be positive for the reulst to make sense.
#' @return `<numeric>` vector (or matrix) of abundances.
#' @examples
#' ricker_reproduction_model(
#'   abundance = 10,
#'   reproduction_rate = 0.25,
#'   carrying_capacity = 100
#' )
#' ricker_reproduction_model(
#'   abundance = matrix(10, 10, 10),
#'   reproduction_rate =  matrix(seq(-0.5, 0.5, length.out = 100), 10, 10),
#'   carrying_capacity =  matrix(100, 10, 10)
#' )
#' @references Cabral, J.S. & Schurr, F.M. (2010) Estimating demographic
#' models for the range dynamics of plant species.
#' Global Ecology and Biogeography, 19, 85–97.
#' <doi:10.1111/j.1466-8238.2009.00492.x>
#'
#' Original model:
#' Ricker, W.E. (1954) Stock and recruitment.
#' Journal of the Fisheries Research Board of Canada, 11, 559–623.
#' <doi:10.1139/f54-039>
#' @export
ricker_reproduction_model <- function(abundance, reproduction_rate, carrying_capacity) {
    .Call('_metaRange_ricker_reproduction_model', PACKAGE = 'metaRange', abundance, reproduction_rate, carrying_capacity)
}

